Repository googleinterns/step194-2020, pull requests merged in 2020-08, with the labels that each got.

#62 In Chat notifications
  .firebaserc
  firebase.json
  functions/.gitignore
  functions/index.js
  functions/package-lock.json
  functions/package.json
  package-lock.json
  package.json
Labels: enhancement

#65 style adjustments for smaller screens
  src/main/webapp/chat_style.css
  src/main/webapp/index_style.css
Labels: frontend

#66 Allow video container to resize and scroll if needed
  src/main/webapp/firebase-chat.js
  src/main/webapp/queue_style.css
Labels: frontend

#68 Fix repeating chat notifications
  functions/notifications.js
  functions/package.json
  src/main/webapp/iframe.js
Labels: bug
